### ISSUE TITLE
Photomechanic for Munki doesn`t work

### ISSUE THREAD

**Issue by snowwalker1988** [autopkg/eholtam-recipes#4]
Hi,
it is great that you made an recipe for Photomechanic for Munki.

But I have the problem that it doesn´t work.
I use AutoPkgr and when I run the recipe I can not see Photomechanic with the actual version in Munki.

Do you have some idea?

**Comment by poundbangbash** [comment]
I just cleared out all imported version from my munki repo and re-ran the .munki recipe.  It imported version 5.0 and this is the contents of the pkginfo file:

```
    <key>installs</key>
    <array>
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.camerabits.PhotoMechanic</string>
            <key>CFBundleName</key>
            <string>Photo Mechanic 5</string>
            <key>CFBundleShortVersionString</key>
            <string>5.0</string>
            <key>CFBundleVersion</key>
            <string>5000</string>
            <key>minosversion</key>
            <string>10.6</string>
            <key>path</key>
            <string>/Applications/Photo Mechanic 5.app</string>
            <key>type</key>
            <string>application</string>
            <key>version_comparison_key</key>
            <string>CFBundleShortVersionString</string>
        </dict>
    </array>
    <key>items_to_copy</key>
    <array>
        <dict>
            <key>destination_path</key>
            <string>/Applications</string>
            <key>source_item</key>
            <string>Photo Mechanic 5.app</string>
        </dict>
    </array>
    <key>minimum_os_version</key>
    <string>10.6.8</string>
    <key>name</key>
    <string>PhotoMechanic</string>
    <key>unattended_install</key>
    <true/>
    <key>uninstall_method</key>
    <string>remove_copied_items</string>
    <key>uninstallable</key>
    <true/>
    <key>version</key>
    <string>5.0</string>
```

Where are you not seeing the version? What is in the pkginfo file in your munki repo?

**Comment by snowwalker1988** [comment]
I use MunkiAdmin and there I can't see the Photomechanic. But also not in the munkirepo.
Before I had the version 5.0 R16765 in the munkirepo which I put in by terminal with munkiimport.
Also after deleting them in the munkirepo your recipe didn't work for me.

But the actual version 5.0 R17338 is downloaded by your recipe to Users/Username/Library/AutoPkg/Cache/...

I think also a problem is, that the installs key of version 5.0 R16765 is the same as in the new build 5.0 R17338. Do you have any idea therefore?

In both version you find in the packageinfo:

`<key>installs</key>
    <array>
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.camerabits.PhotoMechanic</string>
            <key>CFBundleName</key>
            <string>Photo Mechanic 5</string>
            <key>CFBundleShortVersionString</key>
            <string>5.0</string>
            <key>CFBundleVersion</key>
            <string>5000</string>
            <key>minosversion</key>
            <string>10.6</string>
            <key>path</key>
            <string>/Applications/Photo Mechanic 5.app</string>
            <key>type</key>
            <string>application</string>
            <key>version_comparison_key</key>
            <string>CFBundleShortVersionString</string>
        </dict>
    </array>`

**Comment by poundbangbash** [comment]
Interesting. Looks like we've stumbled upon bad software packaging. They released a new "version" but didn't increment any of the versioning information in the actual package itself.  If that's the case then autopkg/munkiimport is doing the right thing and not importing the application because, to the system, it appears to be the same version.  To confirm that can you run the following and post the output removing any confidential information (server names, etc).  `autopkg run -vv PhotoMechanic.munki`

I didn't have a previous version to test against when I wrote the recipe.  Can you extract the 5.0 R16765 installer from your repo and post it somewhere I can download it so I can have that as a baseline in my test repo?

Is the build version you see just in the name of the dmg that gets downloaded?

I'd also suggest emailing the developer and inform them of the importance of proper versioning.  We may or may not be able to write workarounds but if they just versioned correctly we wouldn't have to.

-Eric

**Comment by poundbangbash** [comment]
I was able to download an older version from the camerabits site by modifying the URL and could replicate the issue you're seeing.

I've re-worked the recipes significantly to address Camera Bits' application versioning issue. To do that I parsed the build version from the download dmg URL and then used autopkg to create a .pkg from from the downloaded app and give it the pkg a version of version.build (5.0.17338) and import that into munki. Each new build should increment the version to 5.0.build#.

I've updated the recipes in my repo so you'll need to update the `eholtam-recipes` repo in Autopkgr.  Then try running the munki recipe again.

Please give this a go and let me know if it addresses your issues.

**Comment by snowwalker1988** [comment]
Thanks for your help at first.
Now I get a .pkg in munki, but when I have installed build 16765 on the client before and then put the new build in munki to the client the client didn't get the new build.
Only when I set the installskey in the plist for build 17338 it is installed.

But then I have the problem that munki trys the installation many times although the new version is installed.
I think it is because "CFBundleShortVersionString" in the installs key is for all versions 5.0.
But I must use the installs key to check the installed versions. Or do you know another method?

So the developer have to do something or do you have an idea for a workaround?

Best regards
Marcus

**Comment by poundbangbash** [comment]
I'm not seeing the same issue as you here.  I manually added the older build 16765 to my munki repo by `munkiimport`ing the .dmg like the previous recipe did.  I then had that version install on a client.  I added the new build 17338 to munki via the recipe and setup the pkginfo to have the same `name` to match the previous version so it would appear as an update to the client.  On the client the pkg version was downloaded and installed without any other modifications to the pkginfo.  The pkginfo that was created when running autopkg didn't have an Installs array for me, just a receipt.  

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>_metadata</key>
    <dict>
        <key>created_by</key>
        <string>admin</string>
        <key>creation_date</key>
        <date>2016-04-26T22:27:57Z</date>
        <key>munki_version</key>
        <string>2.6.1.2693</string>
        <key>os_version</key>
        <string>10.11.4</string>
    </dict>
    <key>autoremove</key>
    <false/>
    <key>catalogs</key>
    <array>
        <string>development-camerabits-photomechanic</string>
    </array>
    <key>description</key>
    <string>Photo Mechanic is a standalone image browser and workflow accelerator that lets you view your digital photos with convenience and speed.</string>
    <key>display_name</key>
    <string>Photo Mechanic</string>
    <key>installed_size</key>
    <integer>65718</integer>
    <key>installer_item_hash</key>
    <string>3c8bf2b6d5be2fcff3f3090c60c1e18809467deb7369562dfdf17fd6919ea380</string>
    <key>installer_item_location</key>
    <string>apps/camerabits/PhotoMechanic-5.0.17338.pkg</string>
    <key>installer_item_size</key>
    <integer>26412</integer>
    <key>minimum_os_version</key>
    <string>10.6.8</string>
    <key>name</key>
    <string>PhotoMechanic</string>
    <key>receipts</key>
    <array>
        <dict>
            <key>installed_size</key>
            <integer>65718</integer>
            <key>packageid</key>
            <string>com.github.autopkg.camerabits.photomechanic.pkg</string>
            <key>version</key>
            <string>5.0.17338</string>
        </dict>
    </array>
    <key>unattended_install</key>
    <true/>
    <key>uninstall_method</key>
    <string>removepackages</string>
    <key>uninstallable</key>
    <true/>
    <key>version</key>
    <string>5.0.17338</string>
</dict>
</plist>
```

Ultimately the developer needs to version their application correctly, yes.  This workaround is a patch for their bad versioning.

**Comment by snowwalker1988** [comment]
This didn't work for me, but I don't know why.

Here is my pkginfo for 16765:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>_metadata</key>
    <dict>
        <key>created_by</key>
        <string>it-support</string>
        <key>creation_date</key>
        <date>2015-10-07T16:22:50Z</date>
        <key>munki_version</key>
        <string>2.3.1.2535</string>
        <key>os_version</key>
        <string>10.10.5</string>
    </dict>
    <key>autoremove</key>
    <false/>
    <key>catalogs</key>
    <array>
        <string>testing</string>
    </array>
    <key>category</key>
    <string>Picture</string>
    <key>description</key>
    <string>photo ingesting, tagging and browsing tool</string>
    <key>developer</key>
    <string>Camerabits</string>
    <key>display_name</key>
    <string>Photo Mechanic 5</string>
    <key>installer_item_hash</key>
    <string>1f359f3a17da949ea9e8a59740f203120a135ecd78f968061e448473a6a28c17</string>
    <key>installer_item_location</key>
    <string>apps/Camerabits/PhotoMechanic5R16765-5.0 R16765.dmg</string>
    <key>installer_item_size</key>
    <integer>28393</integer>
    <key>installer_type</key>
    <string>copy_from_dmg</string>
    <key>installs</key>
    <array>
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.camerabits.PhotoMechanic</string>
            <key>CFBundleName</key>
            <string>Photo Mechanic 5</string>
            <key>CFBundleShortVersionString</key>
            <string>5.0</string>
            <key>CFBundleVersion</key>
            <string>5000</string>
            <key>minosversion</key>
            <string>10.6.8</string>
            <key>path</key>
            <string>/Applications/Photo Mechanic 5.app</string>
            <key>type</key>
            <string>application</string>
            <key>version_comparison_key</key>
            <string>CFBundleShortVersionString</string>
        </dict>
    </array>
    <key>items_to_copy</key>
    <array>
        <dict>
            <key>destination_path</key>
            <string>/Applications</string>
            <key>source_item</key>
            <string>Photo Mechanic 5.app</string>
        </dict>
    </array>
    <key>minimum_os_version</key>
    <string>10.6.8</string>
    <key>name</key>
    <string>Photo Mechanic 5</string>
    <key>uninstall_method</key>
    <string>remove_copied_items</string>
    <key>uninstallable</key>
    <true/>
    <key>version</key>
    <string>5.0 R16765</string>
</dict>
</plist>`

And here for 17338:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>_metadata</key>
    <dict>
        <key>created_by</key>
        <string>it-support</string>
        <key>creation_date</key>
        <date>2016-04-28T13:53:48Z</date>
        <key>munki_version</key>
        <string>2.6.1.2684</string>
        <key>os_version</key>
        <string>10.11.4</string>
    </dict>
    <key>autoremove</key>
    <false/>
    <key>catalogs</key>
    <array>
        <string>testing</string>
        <string>live</string>
    </array>
    <key>category</key>
    <string>Foto</string>
    <key>description</key>
    <string>Photo Mechanic is a standalone image browser and workflow accelerator that lets you view your digital photos with convenience and speed.</string>
    <key>developer</key>
    <string>Camerabits</string>
    <key>display_name</key>
    <string>Photo Mechanic 5</string>
    <key>icon_name</key>
    <string>Photo Mechanic 5.png</string>
    <key>installed_size</key>
    <integer>65718</integer>
    <key>installer_item_hash</key>
    <string>84310522d51ea1f096fc6046e04c2a1ff837f9effd8c1c451207ce32a5267221</string>
    <key>installer_item_location</key>
    <string>apps/camerabits/PhotoMechanic-5.0.17338.pkg</string>
    <key>installer_item_size</key>
    <integer>26412</integer>
    <key>minimum_os_version</key>
    <string>10.6.8</string>
    <key>name</key>
    <string>Photo Mechanic 5</string>
    <key>receipts</key>
    <array>
        <dict>
            <key>installed_size</key>
            <integer>65718</integer>
            <key>packageid</key>
            <string>com.github.autopkg.camerabits.photomechanic.pkg</string>
            <key>version</key>
            <string>5.0.17338</string>
        </dict>
    </array>
    <key>unattended_install</key>
    <true/>
    <key>uninstall_method</key>
    <string>removepackages</string>
    <key>uninstallable</key>
    <true/>
    <key>version</key>
    <string>5.0.17338</string>
</dict>
</plist>
`

How do you get your code here so structured?

When I put the new version into munki nothing is done.
If I put in an installs key for the new version it is done, but munch tries the installation many times.
I think then it is because munki sees the same version which is installed.

`<key>installs</key>
    <array>
        <dict>
            <key>CFBundleIdentifier</key>
            <string>com.camerabits.PhotoMechanic</string>
            <key>CFBundleName</key>
            <string>Photo Mechanic 5</string>
            <key>CFBundleShortVersionString</key>
            <string>5.0</string>
            <key>CFBundleVersion</key>
            <string>5000</string>
            <key>minosversion</key>
            <string>10.6.8</string>
            <key>path</key>
            <string>/Applications/Photo Mechanic 5.app</string>
            <key>type</key>
            <string>application</string>
            <key>version_comparison_key</key>
            <string>CFBundleShortVersionString</string>
        </dict>
    </array>`

**Comment by poundbangbash** [comment]
The pkginfo for build 17338 looks fine.  The <name> key matches in both versions so the latter should be seen as an updated version for the already installed 16765.

Without adding the installs array to the later version's pkginfo can you run `sudo managedsoftwareupdate -vvvv` on the client that's not detecting the new version to install and post it here?

As for the structure of the XML..what do you use to edit the plist files?  I believe XCode's plist editor makes the output in one long line.  You can reformat it by running the plist thru a conversion and back.
`plutil -convert binary1 /path/to/pkginfo.plist`
`plutil -convert xml1 /path/to/pkginfo.plist`

That will format it with line breaks and indentations.

**Comment by snowwalker1988** [comment]
Now I installed at first 16765 and run it:

`* Processing manifest item Photo Mechanic 5-5.0.16765 for install
    Looking for detail for: Photo Mechanic 5, version 5.0.16765...
    Considering 1 items with name Photo Mechanic 5 from catalog live
    Considering item Photo Mechanic 5, version 5.0.16765 with minimum os version required 10.6.8
    Our OS version is 10.10.5
    Found Photo Mechanic 5, version 5.0.16765 in catalog live
        Found Info.plist at /Applications/Photo Mechanic 5.app/Contents/Info.plist
        Checking /Applications/Photo Mechanic 5.app/Contents/Info.plist for CFBundleShortVersionString 5.0...
        Using version_comparison_key CFBundleShortVersionString
        Installed item has version 5.0
        Installed item is the same.
    Photo Mechanic 5 version 5.0.16765 (or newer) is already installed.
    Looking for updates for: Photo Mechanic 5-5.0.16765
    Looking for updates for: Photo Mechanic 5--5.0.16765
    **Checking for removals**
    ** Processing manifest client_manifest.plist for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest mediatec for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest 01-Standard for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    **Checking for managed updates**
    ** Processing manifest client_manifest.plist for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest mediatec for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest 01-Standard for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/
`

Then I put 17338 into the manifest and run the command:

`* Processing manifest item Photo Mechanic 5 for install
    Looking for detail for: Photo Mechanic 5, version latest...
    Considering 1 items with name Photo Mechanic 5 from catalog live
    Considering item Photo Mechanic 5, version 5.0.17338 with minimum os version required 10.6.8
    Our OS version is 10.10.5
    Found Photo Mechanic 5, version 5.0.17338 in catalog live
    Looking for package com.github.autopkg.camerabits.photomechanic.pkg, version 5.0.17338
    Photo Mechanic 5 version 5.0.17338 (or newer) is already installed.
    Looking for updates for: Photo Mechanic 5
    Looking for updates for: Photo Mechanic 5-5.0.17338
    Looking for updates for: Photo Mechanic 5--5.0.17338
    **Checking for removals**
    ** Processing manifest client_manifest.plist for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest mediatec for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest 01-Standard for managed_uninstalls
    Catalog base URL is: http://IP/munki_repo/catalogs/
    **Checking for managed updates**
    ** Processing manifest client_manifest.plist for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest mediatec for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/
    ** Processing manifest 01-Standard for managed_updates
    Catalog base URL is: http://IP/munki_repo/catalogs/`

But installed is version 16765 when I open Photomechanic and look into About.

For editing those files I use the TextWrangler.

**Comment by poundbangbash** [comment]
Had you previously installed the .pkg the autopkg creates on the machine you're running this from?  The lines `Looking for package com.github.autopkg.camerabits.photomechanic.pkg, version 5.0.17338 Photo Mechanic 5 version 5.0.17338 (or newer) is already installed.` show that it sees the pkg domain of `com.github.autopkg.camerabits.photomechanic.pkg` which is unique to the pkg that gets created out of autopkg.  The only way that would be on the computer is if the autopkg generated .pkg was installed.  You can verify it sees the pkg receipt by running `pgkinfo --pkgs | grep photomechanic`.

If you're in the testing phase with this machine clear out the pkg receipt otherwise it appears that version 17338 is already installed due to the receipt being there even if the application in /Applications is the older version.  When munki installs pkgs it defaults to using checking for pkg receipt versions.  To remove the pkg receipt run the following `sudo pkgutil --forget com.github.autopkg.camerabits.photomechanic.pkg`.  Then run `sudo managedsoftwareupdate -vvv` again.  You should see that it downloaded the updated version and is ready to install.  To install after it has downloaded run `sudo managedsoftwareupdate --installonly`.

**Comment by snowwalker1988** [comment]
Yes I had. On this machine I had this problem first installing many times.
I have found this receipt.
Thanks for this hint.

This also explains now for me why in past some pkg maybe don't get installed.
So you helped me a lot. Big thanks for it.

In the mean time I also wrote to the Photomechanic developer and got this answer:

> Hi Marcus,
> 
> I checked with the programmers about the Photo Mechanic build number and that is compiled into the application. Probably the best way to determine the build number is to look at the creation date of the Photo Mechanic application. If you can compare the creation dates, then you can determine if there is a newer version available. I will let you know if the programmers add an option to check the build number without launching Photo Mechanic. Please let me know if you have anymore questions with Photo Mechanic.
> Best regards,
> 
> —Bob

**Comment by poundbangbash** [comment]
Sounds like the problem has been addressed for this thread so I'll close it. 

If you need further help with autopkg or munki there are many available, including myself, that are willing to help on the macadmins Slack instance in realtime. You can join us at http://macadmins.org
